server:
  port: 8080
  servlet:
    context-path: /auth


spring:
  application:
    name: AuthService
  datasource:
    url: "jdbc:mysql://localhost:3306/sphere_auth"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

